#!/bin/sh

# build
#	Simple wiringPi build and install script
#
#	Copyright (c) 2012-2015 Gordon Henderson
#################################################################################
# This file is part of wiringPi:
#	Wiring Compatable library for the Raspberry Pi
#
#    wiringPi is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    wiringPi is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with wiringPi.  If not, see <http://www.gnu.org/licenses/>.
#################################################################################
#
# wiringPi is designed to run on a Raspberry Pi only.
#	However if you're clever enough to actually look at this script to
#	see why it's not building for you, then good luck.
#
#################################################################################

check_make_ok() {
  if [ $? != 0 ]; then
    echo ""
    echo "Make Failed..."
    echo "Please check the messages and fix any problems. If you're still stuck,"
    echo "then please email all the output and as many details as you can to"
    echo "  projects@drogon.net"
    exit 1
  fi
}

  echo "wiringPi Build script"
  echo "====================="

if [ x$1 = "xclean" ]; then
  echo
  echo "WiringPi Library"
  cd wiringPi
  make clean
  check_make_ok
  echo
  echo "WiringPi Devices Library"
  cd ../devLib
  make clean
  check_make_ok
  echo
  echo "GPIO Utility"
  cd ../gpio
  make clean
  check_make_ok

else
  echo
  echo "WiringPi Library"
  cd wiringPi
  make uninstall
  if [ x$1 = "xstatic" ]; then
    make -j5 static
    check_make_ok
    make install-static
  else
    make -j5
    check_make_ok
    make install
  fi
  check_make_ok

  echo
  echo "WiringPi Devices Library"
  cd ../devLib
  make uninstall
  if [ x$1 = "xstatic" ]; then
    make -j5 static
    check_make_ok
    make install-static
  else
    make -j5
    check_make_ok
    make install
  fi
  check_make_ok

  echo
  echo "GPIO Utility"
  cd ../gpio
  make -j5
  check_make_ok
  make install
  check_make_ok

echo
echo All Done.
echo ""
echo "NOTE: To compile programs with wiringPi, you need to add:"
echo "    -lwiringPi"
echo "  to your compile line(s) To use the Gertboard, MaxDetect, etc."
echo "  code (the devLib), you need to also add:"
echo "    -lwiringPiDev"
echo "  to your compile line(s)."
echo ""
fi
